# Generated by Django 3.2.5 on 2021-08-09 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=25)),
                ('total_amount', models.IntegerField(default=0)),
                ('collection_date', models.DateField(default=datetime.date.today)),
                ('balance_amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=25)),
                ('brand_manager', models.CharField(max_length=25)),
                ('customer_name', models.CharField(max_length=25)),
                ('narration', models.CharField(max_length=25)),
                ('amount', models.IntegerField(default=0)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('balance_amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
    ]
