# Generated by Django 3.2.5 on 2021-08-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0002_alter_invoices_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='reference',
            field=models.CharField(max_length=25),
        ),
    ]
