# Generated by Django 3.2.5 on 2021-08-10 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0003_alter_invoices_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.collections'),
        ),
    ]
