# Generated by Django 3.2.5 on 2021-08-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0006_alter_invoices_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='brand_manager',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='customer_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='narration',
            field=models.CharField(max_length=250),
        ),
    ]
