# Generated by Django 3.2.5 on 2021-08-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0007_auto_20210810_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='balance_amount',
        ),
    ]
