# Generated by Django 3.2.5 on 2021-08-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0008_remove_invoices_balance_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='total_amount',
            new_name='collection_amount',
        ),
    ]
