# Generated by Django 3.2.5 on 2021-08-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0009_rename_total_amount_collections_collection_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='balance_amount',
        ),
    ]
